---
- include: preflight.yml

- include: prepare.yml
  become: yes

# --------------------------------------------------
# Install/upgrade 'prometheus' app files
# --------------------------------------------------
- include: install.yml
  become: yes

# --------------------------------------------------
# Create a configuraiton file (prometheus.yml)
# --------------------------------------------------
- include: config.yml
  become: yes

# --------------------------------------------------
# Install and run the service
# --------------------------------------------------
- name: Install service
  template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: start prometheus

- name: Enable service
  service:
    name: prometheus
    enabled: yes
  become: yes

- name: Force all handlers to run
  meta: flush_handlers

# Make sure the service is running.
# Otherwise, report error
- name: Verify if service is running
  service:
    name: prometheus
    state: started
  become: yes
