---
- name: "Gather os specific variables ({{ ansible_distribution }} - {{ ansible_distribution_major_version }})"
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "../vars/{{ ansible_distribution }}.yml"

# ---------------------------------------------
# Install dependencies
# ---------------------------------------------
- include: dependencies.yml
  become: yes

# --------------------------------------------------
# Create user/group
# --------------------------------------------------
- name: "Add prometheus group '{{ prometheus_group }}'"
  group:
    name: "{{ prometheus_group }}"
    state: present
  when: prometheus_group != 'root'

- name: "Add prometheus user '{{ prometheus_user }}'"
  user:
    name: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    comment: "Prometheus"
    shell: /bin/false
    system: yes
  when: prometheus_user != 'root'

# --------------------------------------------------
# Initialize the installation/upgrade process
# --------------------------------------------------
- name: Initialize the deploy root and gather facts
  deploy_helper:
    path: "{{ prometheus_install_dir }}"
    release: "{{ prometheus_version }}"
    mode: u=rwX,g=rX,o=rX
  become: yes

# --------------------------------------------------
# Install/upgrade 'prometheus' app files
# --------------------------------------------------
- include: install.yml
  become: yes

# --------------------------------------------------
# Cleanup old and unfinished releases
# --------------------------------------------------
- name: Cleanup old releases
  deploy_helper:
    path: "{{ prometheus_install_dir }}"
    release: '{{ deploy_helper.new_release }}'
    state: finalize
    keep_releases: 10
  notify: 
    - restart prometheus
  become: yes