---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted
  become: true

- name: reload prometheus
  service:
    name: prometheus
    state: reloaded
  become: true

- name: start prometheus
  service:
    name: prometheus
    state: started
  become: true
