---
- name: restart prometheus
  service: 
    name: prometheus
    state: restarted
  become: yes

- name: reload prometheus
  service: 
    name: prometheus
    state: reloaded
  become: yes

- name: start prometheus
  service: 
    name: prometheus
    state: started
  become: yes
