---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify if service is running
      service: 
        name: prometheus
        state: started

    - name: Verify prometheus web interface
      uri:
        url: "http://localhost:9090/metrics"
        method: GET
        status_code: 200
        return_content: yes
      register: prometheus_http_result
      until: prometheus_http_result.status == 200
      failed_when: '"prometheus_build_info" not in prometheus_http_result.content'
      retries: 30
      delay: 1



